
export const businessCategories = [
    { value: 'accounting', label: 'Accounting' },
    { value: 'automotive', label: 'Automotive' },
    { value: 'beauty-salon', label: 'Beauty Salon' },
    { value: 'bike-shop', label: 'Bike Shop' },
    { value: 'bookstore', label: 'Bookstore' },
    { value: 'cafes', label: 'Cafes'},
    { value: 'charity', label: 'Charity' },
    { value: 'clothing', label: 'Clothing' },
    { value: 'community-group', label: 'Community Group' },
    { value: 'electronics', label: 'Electronics' },
    { value: 'entertainment', label: 'Entertainment' },
    { value: 'fitness', label: 'Fitness' },
    { value: 'florist', label: 'Florist' },
    { value: 'food', label: 'Food & Drink' },
    { value: 'furniture', label: 'Furniture' },
    { value: 'housing-association', label: 'Housing Association' },
    { value: 'jewellery', label: 'Jewellery' },
    { value: 'music-store', label: 'Music Store' },
    { value: 'optician', label: 'Optician' },
    { value: 'outdoors', label: 'Outdoors' },
    { value: 'pet-services', label: 'Pet Services' },
    { value: 'photography', label: 'Photography' },
    { value: 'professional-services', label: 'Professional Services' },
    { value: 'restaurants', label: 'Restaurants'},
    { value: 'shopping', label: 'Shopping' },
    { value: 'shoe-store', label: 'Shoe Store' },
    { value: 'stationery', label: 'Stationery' },
    { value: 'toys-hobbies', label: 'Toys & Hobbies' },
    { value: 'other', label: 'Other' },
];
